# Source https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spamooor
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: spamooor-cronjobs
  source:
    repoURL: https://github.com/astriaorg/spamooor.git
    targetRevision: quasystaty1/spam-main-dawn-1
    path: charts/spamooor-cronjobs
    helm:
      valueFiles:
      - values.yaml
      # parameters:  # Paramters to override default values in values.yaml
      # - name: jobs.erctxsjob.image.tag
      #   value: latest
      # - name: jobs.eoatxsjob.image.tag
      #   value: latest
      # - name: jobs.univ2txsjob.image.tag
      #   value: latest
      # - name: jobs.gasburnertxsjob.image.tag
      #   value: latest
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        # argocd.argoproj.io/instance: <$ARGOCD_APP_NAME>
        argocd.argoproj.io/instance: spamooor
      annotations:
        # argocd.argoproj.io/tracking-id: <$ARGOCD_APP_NAME>:/Namespace:$ARGOCD_APP_NAMESPACE
        argocd.argoproj.io/tracking-id: spamooor/Namespace:spamooor-cronjobs
